development:
  adapter:  postgresql
  host:     postgres
  encoding: unicode
  database: friends_book_development
  pool:     5
  username: postgres
  # NOTE: place your credentials at safe place
  password: postgres
  port:     5432

test: &test
  adapter: sqlite3
  host: localhost
  database: friends_book_test

cucumber:
  <<: *test
